language: python
# Uncomment this if you want to specify Python 3.11
# python:
# - "3.11"
install:
- pip install -r requirements.txt
script:
- black --check . # Run black for formatting check
- flake8 --max-line-length=150 . # Run flake8 for linting
- coverage run manage.py test # Run tests and measure coverage
- env # Show environment variables (helpful for debugging)
after_success:
- coveralls # Upload coverage report to Coveralls
deploy:
provider: elasticbeanstalk
access_key_id: AKIATPLQ2AFEV3UH6KT2
secret_access_key: ONwIzmckUIiPUc/KGgOjpeStBibKYUUrYLNuYvnI
region: us-west-1
app: nocheckthing
env: django-env5
bucket_name: elasticbeanstalk-us-west-1-239144141129 # Your S3 bucket for deployment
on:
repo: poojathakur00/swe1-app 
branch: master 
skip_cleanup: 'true'
