language: python
# Uncomment this if you want to specify Python 3.11
python:
- '3.9'
install:
- pip install -r requirements.txt
- pip install black flake8 coverage coveralls 
script:
#- black --check . # Run black for formatting check
- flake8 --max-line-length=150 . # Run flake8 for linting
- coverage run manage.py test # Run tests and measure coverage
- env # Show environment variables (helpful for debugging)
after_success:
- coveralls # Upload coverage report to Coveralls
deploy:
- skip_cleanup: 'true'
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-west-1
  app: newebapp
  env: my-env
  bucket_name: elasticbeanstalk-us-west-1-239144141129
  on:
    repo: poojathakur00/swe1-app
    branch: master
