language: python
install:
- pip install -r requirements.txt
script:
- black --check . 
- flake8 --max-line-length=150 . 
- coverage run manage.py test
- env
after_success:
- coveralls 
deploy:
provider: elasticbeanstalk
access_key_id: $AWS_ID
secret_access_key: $AWS_KEY
region: us-west-1
app: nocheckthing
env: django-env5
bucket_name: elasticbeanstalk-us-west-1-239144141129 # Your S3 bucket for deployment
on:
repo: poojathakur00/swe1-app 
branch: master 
skip_cleanup: 'true'
