name: Django CI

on:
  push:
    branches:
      - master  # or your default branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Set the correct Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py migrate
        python manage.py test

